name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: gha-runner-scale-set
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go build main.go -o great-iterator
      - uses: VAllens/gitea-publish-generic-packages@v1
        with:
          api_url: 'https://gitea.hnatekmar.xyz'
          token: '${{ secrets.GITEA_TOKEN }}''
          files: |- 
            great-iterator

