name: 'Code review'

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  test-linux:
    runs-on: gha-runner-scale-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
          check-latest: 'true'
      - run: go test

  test-osx:
    runs-on: macOS
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
          check-latest: 'true'
      - run: go test

  review-action:
    runs-on: gha-runner-scale-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Code Review
        uses: tomisacat/ai_code_review@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OLLAMA_ADDRESS: 'https://ollama.hnatekmar.xyz'
          LLM_MODEL: 'deepseek-coder-v2:16b'
