name: Release

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:


  build:
    runs-on: gha-runner-scale-set
    strategy:
      matrix:
        GOOS: ['linux', 'darwin', 'windows']
        GOARCH: ['arm64', 'amd64']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
          check-latest: 'true'
      - run: GOOS=${{matrix.GOOS}} GOARCH=${{matrix.GOARCH}} go build -o great-iterator@${{matrix.GOOS}}-${{matrix.GOARCH}} main.go

    runs-on: gha-runner-scale-set

  release:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged || github.event_name == 'workflow_dispatch'
    runs-on: gha-runner-scale-set
    needs: [build]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
      - uses: VAllens/gitea-publish-generic-packages@v1
        with:
          api_url: 'https://gitea.hnatekmar.xyz/api/v1/'
          owner: 'martin'
          package_version: '${{ pre-release.steps.semver.outputs.next }}'
          package_name: '${{ github.event.repository.name }}'
          token: '${{ secrets.GITEA_TOKEN }}'
          files: |-
            great-iterator*

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: '${{ pre-release.steps.semver.outputs.next }}'
          tag: '${{ pre-release.steps.semver.outputs.next }}'
          body: |
            Linux (arm64): https://gitea.hnatekmar.xyz/api/packages/martin/generic/${{github.event.repository.name}}/${{pre-release.steps.semver.outputs.next}}/great-iterator@linux-arm64
            Linux (x86_64): https://gitea.hnatekmar.xyz/api/packages/martin/generic/${{github.event.repository.name}}/${{pre-release.steps.semver.outputs.next}}/great-iterator@linux-amd64
            Mac (arm64): https://gitea.hnatekmar.xyz/api/packages/martin/generic/${{github.event.repository.name}}/${{pre-release.steps.semver.outputs.next}}/great-iterator@darwin-arm64
            Mac (x86_64): https://gitea.hnatekmar.xyz/api/packages/martin/generic/${{github.event.repository.name}}/${{pre-release.steps.semver.outputs.next}}/great-iterator@darwin-amd64
            Windows (arm64): https://gitea.hnatekmar.xyz/api/packages/martin/generic/${{github.event.repository.name}}/${{pre-release.steps.semver.outputs.next}}/great-iterator@windows-arm64
            Windows (x86_64): https://gitea.hnatekmar.xyz/api/packages/martin/generic/${{github.event.repository.name}}/${{pre-release.steps.semver.outputs.next}}/great-iterator@windows-amd64
          token: ${{ github.token }}
