name: Release

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  pre-release:
    runs-on: gha-runner-scale-set

    if: github.event_name == 'pull_request' && github.event.pull_request.merged || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main

      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
          check-latest: 'true'

  build:
    needs: pre-release
    strategy:
      matrix:
        GOOS: ['linux', 'darwin', 'windows']
        GOARCH: ['arm', 'amd64']
    steps:
      - run: GOOS=${{matrix.GOOS}} GOARCH=${{matrix.GOOARCH}} go build -o great-iterator@${{matrix.GOOS}}-${{matrix.GOARCH}} main.go

  release:
    needs: build
    steps:
      - uses: VAllens/gitea-publish-generic-packages@v1
        with:
          api_url: 'https://gitea.hnatekmar.xyz/api/v1/'
          owner: 'martin'
          package_version: '${{ steps.semver.outputs.next }}'
          package_name: '${{ github.event.repository.name }}'
          token: '${{ secrets.GITEA_TOKEN }}'
          files: |-
            great-iterator*

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ steps.semver.outputs.next }}
          tag: ${{ steps.semver.outputs.next }}
          body: |
            Linux (x86_64): https://gitea.hnatekmar.xyz/api/packages/martin/generic/${{github.event.repository.name}}/${{ steps.semver.outputs.next }}/great-iterator
            Mac (arm): https://gitea.hnatekmar.xyz/api/packages/martin/generic/${{github.event.repository.name}}/${{ steps.semver.outputs.next }}/great-iterator
            Windows (x86_64): https://gitea.hnatekmar.xyz/api/packages/martin/generic/${{github.event.repository.name}}/${{ steps.semver.outputs.next }}/great-iterator
          token: ${{ github.token }}
