name: Release

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: gha-runner-scale-set

    if: github.event.pull_request.merged

    steps:
      - uses: actions/checkout@v4
      - name: Tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}