name: Release

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  tag:
    runs-on: gha-runner-scale-set

    if: github.event_name == 'pull_request' && github.event.pull_request.merged || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - name: Tag
        uses: ietf-tools/semver-action@v1
        with:
          branch: 'main'
          token: ${{ secrets.GITHUB_TOKEN }}